# Generated by Django 3.1.1 on 2020-09-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentCollector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedComment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('article', models.CharField(max_length=1000)),
                ('removed', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=4000)),
                ('subject', models.CharField(max_length=500)),
            ],
        ),
    ]
